### ISSUE TITLE
Error on installing package.

### ISSUE THREAD

**Issue by delfuria** [DevExpress/DevExpress.Mvvm.Free#5]
Hi,
i'm trying to install the package but i get this error:
......
Added file 'app.config' to project 'SD.DXWPFLibrary'.
Install failed. Rolling back...
Removed package 'DevExpressMvvm 15.1.4' from 'packages.config'
Removed reference 'DevExpress.Mvvm.dll' from project 'SD.DXWPFLibrary'
Removed reference 'DevExpress.Mvvm.UI.dll' from project 'SD.DXWPFLibrary'
Removing package 'DevExpressMvvm 15.1.4' from folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages'
Removed file 'DevExpressMvvm.15.1.4.nupkg' from folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages\DevExpressMvvm.15.1.4.0'.
Removed folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages\DevExpressMvvm.15.1.4.0'.
Removed package 'DevExpressMvvm 15.1.4' from folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages'
System.Runtime.InteropServices.COMException (0x80004005): Cannot add the file 'app.config'. There is already a linked file in this folder with the same name.
   at EnvDTE.ProjectItems.AddFromFileCopy(String FilePath)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFileToContainer(String fullPath, String folderPath, ProjectItems container)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<AddFileToProjectAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<>c__DisplayClass26_0.<<AddFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFile(String path, Stream stream)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.Save(XDocument document)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.AddBindingRedirects(IEnumerable`1 bindingRedirects)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<<AddBindingRedirects>b__55_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddBindingRedirects()
   at NuGet.ProjectManagement.MSBuildNuGetProject.PostProcessAsync(INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

**Comment by AlexChuev** [comment]
Hi Stefano,

I've just checked the package in Visual Studio 2013 & 2015, and everything was installed correctly on my side. Please clarify the following points, so that I can narrow down the issue further:

1. What Windows and Visual Studio version are you working with?
2. Does the issue occur in a particular project or in any project created in Visual Studio?
3. If the issue only occurs in a particular project, can you share this project with me?

I look forward to hearing from you.

Thanks,
Alex

**Comment by delfuria** [comment]
Hi, and thanks for the reply.
1) The error occurs on VS 2015 Enterprise & Win 10 pro
2) The error occurs in a specific project 
3) i cannot share the project because it belong to a solution with 109 project 
Please let me know if i can help in any way.

**Comment by AlexChuev** [comment]
Hi Stefano,

I would appreciate your answering a few more questions:

1) Does the project in question have any other references to other DevExpress libraries? If so, which ones?
2) What .NET Framework version does the project target?
3) Are you able to successfully add other packages to this project?

Thanks for your help.

Alex

**Comment by delfuria** [comment]
Hi again,
1) The project references a lots of Devexpress Libraries
2) The target is 4.5.1
3) no, in my solution no project is able to add the package.

I think that the problem is when the package try to add the app.config file to the project while the project have it's own app.config file (or a link to a "shared" app.config).
Why you need to add the app.config files ?

**Comment by delfuria** [comment]
This is the full log of the package manager 
---
Attempting to gather dependencies information for package 'DevExpressMvvm.15.1.4' with respect to project 'Test Application\TestConsoleDelfo', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'DevExpressMvvm.15.1.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'DevExpressMvvm.15.1.4'
Resolved actions to install package 'DevExpressMvvm.15.1.4'
For adding package 'DevExpressMvvm.15.1.4' to project 'TestConsoleDelfo' that targets 'net451'.
For adding package 'DevExpressMvvm.15.1.4' to project 'TestConsoleDelfo' that targets 'net451'.
Adding package 'DevExpressMvvm.15.1.4' to folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages'
Added package 'DevExpressMvvm.15.1.4' to folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages'
Added reference 'DevExpress.Mvvm' to project 'TestConsoleDelfo'.
Added reference 'DevExpress.Mvvm.UI' to project 'TestConsoleDelfo'.
Added package 'DevExpressMvvm.15.1.4' to 'packages.config'
Successfully installed 'DevExpressMvvm 15.1.4' to TestConsoleDelfo
Added file 'app.config'.
Install failed. Rolling back...
Removed package 'DevExpressMvvm 15.1.4' from 'packages.config'
Removed reference 'DevExpress.Mvvm.dll' from project 'TestConsoleDelfo'
Removed reference 'DevExpress.Mvvm.UI.dll' from project 'TestConsoleDelfo'
Removing package 'DevExpressMvvm 15.1.4' from folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages'
Removed file 'DevExpressMvvm.15.1.4.nupkg' from folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages\DevExpressMvvm.15.1.4.0'.
Removed folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages\DevExpressMvvm.15.1.4.0'.
Removed package 'DevExpressMvvm 15.1.4' from folder 'C:\Lavori\Stoa\Metalpro\B2K.NET\B2K.NET\packages'
System.Runtime.InteropServices.COMException (0x80004005): Cannot add the file 'app.config'. There is already a linked file in this folder with the same name.
   at EnvDTE.ProjectItems.AddFromFileCopy(String FilePath)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFileToContainer(String fullPath, String folderPath, ProjectItems container)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<AddFileToProjectAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<>c__DisplayClass26_0.<<AddFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFile(String path, Stream stream)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.Save(XDocument document)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.AddBindingRedirects(IEnumerable`1 bindingRedirects)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<<AddBindingRedirects>b__55_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddBindingRedirects()
   at NuGet.ProjectManagement.MSBuildNuGetProject.PostProcessAsync(INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

---

**Comment by AlexChuev** [comment]
Hi Stefano,

The DevExpressMvvm package should not modify the app.config file or add it if there is none in the project. Can you please check if you are able to add other packages (e.g., Entity Framework) to your project?

In addition, clarify why you need to install the DevExpressMvvm package if you already reference DevExpress assemblies (the DevExpress MVVM Framework is included with DevExpress WPF and WinForms components).

Thanks,
Alex

**Comment by delfuria** [comment]
Hi,
after some google's search i think that is a Nuget bug:
https://github.com/NuGet/Home/issues/1119
https://github.com/NuGet/Home/issues/1111

so i hope that they'll release a new version asap.
Anyway i need to install this package because i need this method
DevExpress.Mvvm.UI.Native.LayoutHelper.FindLayoutOrVisualParentObject
Thanks for all

**Comment by AlexChuev** [comment]
Hi Stefano,

I hope that the next Nuget version fixes the package installation issue.

I've created a support ticket on your behalf on DevExpress forums to discuss the use of the FindLayoutOrVisualParentObject method: https://isc.devexpress.com/Thread/WorkplaceDetails/T279049. Please check my answer there.

Thanks,
Alex

**Comment by delfuria** [comment]
Hi,
thanks for the reply.
I have contacted the NuGet's team and the last nightly build (still unpublished) solve the issue.
Thanks again for the support.
